### ISSUE TITLE
WorkGroup=primary is missing in JDBC connection

### ISSUE THREAD

**Issue by frschwab** [exasol/athena-virtual-schema#7]
It seems that meanwhile it is mandatory to define a WorkGroup. In my case, queries wouldn't run without this parameter.

**Comment by AnastasiiaSergienko** [comment]
@frschwab could you please provide more information about WorkGroup? I've never used this attribute and connected to Athena without it. What kind of error do you get if you don't provide it?

**Comment by AnastasiiaSergienko** [comment]
I've just tested Athena Virtual Schema and I didn't use WorkGroup=primary. So it looks like it's not mandatory for all cases
