### ISSUE TITLE
Improvement: Docu for jar file name and JDBC connection string and some further guidance

### ISSUE THREAD

**Issue by frschwab** [exasol/athena-virtual-schema#8]
I found out that the current Athena JDBC driver does not have the version number in the name (as suggested in the user guide):
https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html

Also, maybe you could add a section that describes how to connect if you need a VPC endpoint for Athena AND Glue (these are two different endpoints!). The current example only works when no endpoint is needed.

Or just link this article:
https://aws.amazon.com/premiumsupport/knowledge-center/athena-connection-timeout-jdbc-odbc-driver/
Of course it is all fully documented here, also:
https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.23.1000/docs/Simba+Athena+JDBC+Connector+Install+and+Configuration+Guide.pdf

Here an example that I used to make it work for my case:

CREATE OR REPLACE CONNECTION FS_UFOS
TO 'jdbc:awsathena://vpce-06aabbxx-iook4aaao-eu-west-1b.athena.eu-west-1.vpce.amazonaws.com:443;S3OutputLocation=s3://fstestbla1/athena_temp;WorkGroup=primary'
USER 'AKIAKAAKI'
IDENTIFIED BY 'passYpassXpassZ';

**Comment by AnastasiiaSergienko** [comment]
We also want to update:
- instruction about creating a JDBC driver in EXAOperation, it's outdated.
-Add a note that files is not a field of the EXAOperation form, it's just a list of files to be uploaded

**Comment by AnastasiiaSergienko** [comment]
@frschwab I would avoid adding a link to a specific user guide because it has a JDBC driver version in the name. So it can become outdated in the future. We have a link to this page: https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html 
And the page has a link to the guide. I will move the link to the create connection part of our user guide.
